name: COMPILADOR_MAESTRO
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Crear estructura minima
        run: |
          mkdir -p app/src/main/res/values
          echo '<resources><string name="app_name">Reality Compressor</string></resources>' > app/src/main/res/values/strings.xml
          if [ ! -f gradlew ]; then
            touch gradlew
          fi
      - name: Check
        run: ls -R
